// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesUniversidad.Data;

#nullable disable

namespace RazorPagesUniversidad.Migrations
{
    [DbContext(typeof(RazorPagesUniversidadContext))]
    partial class RazorPagesUniversidadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Universidad.Models.Curso", b =>
                {
                    b.Property<int>("Id_curso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Creditos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id_curso");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("Universidad.Models.Estudiante", b =>
                {
                    b.Property<int>("Id_estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_inscripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id_estudiante");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("Universidad.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id_inscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CursoId_curso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstudianteId_estudiante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Grado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_curso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_estudiante")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_inscripcion");

                    b.HasIndex("CursoId_curso");

                    b.HasIndex("EstudianteId_estudiante");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("Universidad.Models.Inscripcion", b =>
                {
                    b.HasOne("Universidad.Models.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CursoId_curso");

                    b.HasOne("Universidad.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId_estudiante");

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Universidad.Models.Curso", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Universidad.Models.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
